# Generated by Django 3.2.9 on 2021-12-05 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userwatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchlist',
            name='cryptowatched',
            field=models.ManyToManyField(blank=True, default=None, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
