# Generated by Django 3.2.9 on 2021-12-05 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userwatchlist_cryptowatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchlist',
            name='cryptowatched',
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='watched_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
